### ISSUE TITLE
Pls add "php_mcrypt" to allow SAML2

### ISSUE THREAD

**Issue by joaocc** [phpipam-docker/phpipam-docker#20] opened 2022-03-29 21:24 UTC
Hi. Running on a container environment, adding SAML2 returns the following error message "php mcrypt extension missing!". Thanks

**Comment by joaocc** [comment] 2022-03-29 21:26
Just found out that libmcrypt stopped being supported in alpine 3.12.

**Comment by GaryAllan** [comment] 2022-03-30 11:04
The 1.5 & nightly images don't need mcrypt.

duplicate of #6

**Closed by GaryAllan** 2022-03-30 11:04 UTC
